### PR TITLE
perf: Change Blog link from /node to /blog/

### PR DESCRIPTION
**Pull request by daniel-beck**
Downstream from https://github.com/jenkins-infra/jenkins.io/pull/7173

### CODE REVIEW

**Comment by daniel-beck** [comment]
https://github.com/jenkins-infra/jenkins-io-components/issues/105

**Comment by daniel-beck** [comment]
Upstream has been merged now.

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Comment by NotMyFault** [comment]
Oh hm I can't merge PRs here. Can you @halkeye, please ?

**Review by halkeye — APPROVED** [review]

**Pull request merged**
