### PR TITLE
feat: Added 'Security' as a tab

### PR DESCRIPTION
**Pull request by Vandit1604**
closes https://github.com/jenkins-infra/jenkins.io/issues/5877 in [jenkins.io](https://github.com/jenkins-infra/jenkins.io/)

### CODE REVIEW

**Comment by halkeye** [comment]
So CI is still broken for a day or two (infra is working on the last bits needed), but overall it sounds like an improvement. I'll ping kevin when the preview sites are working

**Comment by halkeye** [comment]
Also, right now we are using semantic release, so commit messages need to have `fix:` or `feat:` or `chore:` type thing.
Can you update your commit message to `feat: added security as a tab`. I think i can do it on merge, but its easier if you do it in the PR

**Comment by Vandit1604** [comment]
> Also, right now we are using semantic release, so commit messages need to have `fix:` or `feat:` or `chore:` type thing. Can you update your commit message to `feat: added security as a tab`. I think i can do it on merge, but its easier if you do it in the PR

I'll do it now.
I'll correct it

**Comment by halkeye** [comment]
https://deploy-preview-56--jenkins-io-components.netlify.app/?path=/story/example-navbar--all-links-external

@kmartens27 @MarkEWaite

**Review by kmartens27 — APPROVED** [review]
The security tab looks good to me, seems to match text/function and has the discussed sub-links, so approved!

**Comment by halkeye** [comment]
Awesome. I'll merge as soon as releasing is fixed on infra.ci

**Comment by halkeye** [comment]
🤞

**Comment by halkeye** [comment]
So https://cdn.jsdelivr.net caches for 6 hours, and then tells the browser to cache for 20 hours, so you should see changes go live with a hard refresh after 6 hours.

This is exciting, down with github actions!

**Pull request merged**
