### PR TITLE
feat: make Jenkins logo text redirects to jenkins.io on click

### PR DESCRIPTION
**Pull request by krisstern**
Fixes https://github.com/jenkins-infra/contributor-spotlight/issues/42

Redirects users to https://www.jenkins.io/ instead of root `/` upon their clicking of the Jenkins logo text. 

c.c. @kmartens27 @MarkEWaite @alyssat @jmMeessen @gounthar

### CODE REVIEW

**Review by alyssat — APPROVED** [review]
LGTM. Thank you @krisstern for this improvement

**Comment by halkeye** [comment]
I swore i replied to this. I have concerns that all sites will have their "home" button now goto a different site. On plugins.jenkins.io it'll no longer goto the front search page. I'm not going to block it, butI think it needs discussion.

**Review by NotMyFault — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I'm a little surprised at the approval from @NotMyFault since I thought that he preferred the current behavior.

I'm torn between current behavior (link to '/') and the proposed new behavior (link to 'https://www.jenkins.io').  We discussed in documentation office hours today and @gounthar and I were both open to either direction.

@alyssat prefers the change in this pull request so that the clicking the top left Jenkins icon from contributors.jenkins.io or stories.jenkins.io will take the reader to the www.jenkins.io page.  I think that more discussion is needed.  Is there a common behavior that can be referenced from other sites?

**Comment by NotMyFault** [comment]
Apologizes, I clicked the wrong button but cannot dismiss my review :(On 15. Dec 2023, at 01:41, Mark Waite ***@***.***> wrote:﻿
I'm a little surprised at the approval from @NotMyFault since I thought that he preferred the current behavior.
I'm torn between current behavior (link to '/') and the proposed new behavior (link to 'https://www.jenkins.io').  We discussed in documentation office hours today and @gounthar and I were both open to either direction.
@alyssat prefers the change in this pull request so that the clicking the top left Jenkins icon from contributors.jenkins.io or stories.jenkins.io will take the reader to the www.jenkins.io page.  I think that more discussion is needed.  Is there a common behavior that can be referenced from other sites?

**Review by timja — CHANGES_REQUESTED** [review]
Home should go to the current site

**Comment by timja** [comment]
> I think that more discussion is needed. Is there a common behavior that can be referenced from other sites?

I think the Kubernetes site may be similar but when you are on another area of the site they clearly highlight which one you are on so you can get back to the root of that one.

https://kubernetes.io/training/

image

**Comment by halkeye** [comment]
> > I think that more discussion is needed. Is there a common behavior that can be referenced from other sites?
> 
> I think the Kubernetes site may be similar but when you are on another area of the site they clearly highlight which one you are on so you can get back to the root of that one.
> 
> https://kubernetes.io/training/
> 
> image

yea that was one reason I wrote this in the first place. Trying to implement that logic in all the custom html on jenkins.io was frustrating. The javascript version in this component isn't perfect, but its a step in the right direction. Unfortuately it loses the highlighting for sub pages. I had to only highlight for exact matches because prefix matching was breaking too easily.

**Comment by krisstern** [comment]
Not planned

**Pull request closed without merging**
