### PR TITLE
feat: Added `Books` hyperlink in `Resource` section of `Footer`

### PR DESCRIPTION
**Pull request by shashanksah143**
Related to the additional content on the books page added by https://github.com/jenkins-infra/jenkins.io/pull/6043

### CODE REVIEW

**Comment by NotMyFault** [comment]
Do we really need a dedicated footer entry for this? Feels a bit redundant to me, especially when this is shown on other pages than jenkins.io

**Comment by shashanksah143** [comment]
Hi @NotMyFault , I made the changes suggested by Kris Stern. Please refer this PR for more details: https://github.com/jenkins-infra/jenkins.io/issues/6019
Jenkins.io have a traffic of around 1 Million page visit per month. So I thought it will be good to add _books_ page in the resource section of footer as I didn't able to find any web page in jenkins.io which will redirect me to _books_ page.

**Comment by krisstern** [comment]
Originally the link to the books section was on a dropdown in the header, but that got removed along the line. So it would be good to show it somewhere visible to the public, and not hidden as currently is now.

**Comment by krisstern** [comment]
The change looks good in the preview for the UI BTW.

**Comment by halkeye** [comment]
Personally I don't think books is important enough to be visible on every page, but at the very least lets wait till the new content is merged. Right now linking to a page with 2 books from 5-10 years ago isn't really great optics.

**Comment by krisstern** [comment]
Yeah, I see where you are coming from

**Comment by shashanksah143** [comment]
Do we have any updates for this PR?
The `books` page has been updated. Currently, it has 6 books.

**Comment by NotMyFault** [comment]
> Do we have any updates for this PR? The `books` page has been updated. Currently, it has 6 books.

[My](https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1445451776) concerns and [Gavin](https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1449129389)'s comments remain unacknowledged.
If there is no convincing and logical reasoning, why books deserve a separate entry in the footer, this PR can't proceed.

The footer already contains 23 links to various top-class pages. I don't think the book's page is relevant enough for *.jenkins.io visitors to deserve a separate footer entry.
You can use the search bar to find the books page, if you are interested in books about Jenkins.

**Comment by shashanksah143** [comment]
> > Do we have any updates for this PR? The `books` page has been updated. Currently, it has 6 books.
> 
> [My](https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1445451776) concerns and [Gavin](https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1449129389)'s comments remain unacknowledged. If there is no convincing and logical reasoning, why books deserve a separate entry in the footer, this PR can't proceed.
> 
> The footer already contains 23 links to various top-class pages. I don't think the book's page is relevant enough for *.jenkins.io visitors to deserve a separate footer entry. You can use the search bar to find the books page if you are interested in books about Jenkins.

On the current website, there are only two ways to reach the book page, 
1> By searching it in`algolia search`
2> By changing the URL manually  to `/books`

And because of that, the books page will not be easily accessible to the users. 
If the footer is not a good place to put it.  Then we can put it in the navbar, but for that, I will need your guidance on which section of the navbar we should put it.
I am also open to suggestion for any other place where we can put it.

**Comment by MarkEWaite** [comment]
We discussed in Docs Office Hours (Asia) and felt that we should add "Books" to the end of the "Documentation" drop down menu and that we should save vertical space in the drop down by removing the "Tutorial" submenus ("Guided Tour" and "Other tutorials").  The tutorial has "Guided Tour as its first segment and then the other tutorials are the later segments on the same page.

No problem for us that it is not in the footer.

**Comment by shashanksah143** [comment]
> We discussed in Docs Office Hours (Asia) and felt that we should add "Books" to the end of the "Documentation" drop down menu and that we should save vertical space in the drop down by removing the "Tutorial" submenus ("Guided Tour" and "Other tutorials"). The tutorial has "Guided Tour as its first segment and then the other tutorials are the later segments on the same page.
> 
> No problem for us that it is not in the footer.

Thank you for your suggestion. I will make the necessary changes in the navbar.

**Comment by shashanksah143** [comment]
Created a new issue and its corresponding PR to address changes discussed here.
So, closing the PR.

Thank you everyone for your support and guidance.

**Pull request closed without merging**
