### PR TITLE
feat: Adding books hyperlink to documentation section of navbar

### PR DESCRIPTION
**Pull request by shashanksah143**

### CODE REVIEW

**Comment by shashanksah143** [comment]
Hi @NotMyFault, can you please review this PR?

**Review by NotMyFault — COMMENTED** [review]
Works for me, but why does this PR attempt to remove tutorial links?

**Comment by shashanksah143** [comment]
> Works for me, but why does this PR attempt to remove tutorial links?

@MarkEWaite mentioned in the comment, that these two sub-sections should be removed from the dropdown. Please refer this https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1473083640

**Comment by lemeurherve** [comment]
> > Works for me, but why does this PR attempt to remove tutorial links?
> 
> @MarkEWaite mentioned in the comment, that these two sub-sections should be removed from the dropdown. Please refer this [#71 (comment)](https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1473083640)

It would be better to do this removal in a separate pull request.

**Comment by shashanksah143** [comment]
> > > Works for me, but why does this PR attempt to remove tutorial links?
> > 
> > 
> > @MarkEWaite mentioned in the comment, that these two sub-sections should be removed from the dropdown. Please refer this [#71 (comment)](https://github.com/jenkins-infra/jenkins-io-components/pull/71#issuecomment-1473083640)
> 
> It would be better to do this removal in a separate pull request.

Okay, I will create a different PR for that.

**Comment by MarkEWaite** [comment]
> It would be better to do this removal in a separate pull request.

I'm fine with a separate pull request.  When I suggested that the tutorial entries be simplified the same operation as the addition, it was intended to avoid lengthening that already rather long dropdown menu.  However, it is not the longest menu in the list of menus, so two pull requests will make it easier to understand the changes.

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
